server-name=m00gu1
gamemode=survival
force-gamemode=false
difficulty=easy
allow-cheats=true
max-players=8
online-mode=true
allow-list=true
server-port=19132
server-portv6=19133
enable-lan-visibility=true
view-distance=32
tick-distance=4
player-idle-timeout=0
max-threads=0
level-name=Minescape
level-seed=6246468738900744
default-player-permission-level=member
texturepack-required=true
content-log-file-enabled=true
compression-threshold=1
server-authoritative-movement=server-auth
player-movement-score-threshold=20
player-movement-action-direction-threshold=0.85
player-movement-distance-threshold=0.3
player-movement-duration-threshold-in-ms=500
correct-player-movement=false
server-authoritative-block-breaking=false
